#!/bin/tcsh
#
# LSF batch script to run an MPI application
#
#BSUB -P SORE0001        # project code
#BSUB -W 00:06               # wall-clock time (hrs:mins)
#BSUB -n 4                  # number of tasks in job         
#BSUB -R "span[ptile=16]"    # run 16 MPI tasks per node
#BSUB -J fixedgrid            # job name
#BSUB -o fixedgrid.%J.out     # output file name in which %J is replaced by the job ID
#BSUB -e fixedgrid.%J.err     # error file name in which %J is replaced by the job ID
#BSUB -q geyser          # queue

#run the executable
mpirun.lsf python ./fixedgrid.py

