/*----------------------- BEGIN small_parameters.h BEGIN ----------------------*/
/* @file small_parameters.h                                                    */
/* @author jlinford                                                            */
/* @date 2015-04-15 21:17:47.119359                                            */
/* @brief Program parameters                                                   */
/*                                                                             */
/* Integration tolerances, program constants, and species indices.             */
/*                                                                             */
/* This file was generated by Kppa: http://www.paratools.com/Kppa              */
/*-----------------------------------------------------------------------------*/

#ifndef __SMALL_PARAMETERS_H__
#define __SMALL_PARAMETERS_H__



#ifdef __cplusplus
extern "C" {
#endif



/*-----------------------------------------------------------------------------*/
/* Integration tolerances                                                      */
/*-----------------------------------------------------------------------------*/

/* Absolute tolerance */
#define ATOLS            ((float)(1.0))
/* Relative tolerance */
#define RTOLS            ((float)(0.001))


/*-----------------------------------------------------------------------------*/
/* Concentration constants                                                     */
/*-----------------------------------------------------------------------------*/

/* Conversion factor */
#define CFACTOR          ((float)(1.0))
/* Default initialization value for variable species */
#define VAR_DEFAULT      ((float)(0.0))
/* Default initialization value for fixed species */
#define FIX_DEFAULT      ((float)(0.0))


/*-----------------------------------------------------------------------------*/
/* Program constants                                                           */
/*-----------------------------------------------------------------------------*/

/* Species count */
#define NSPEC            ((size_t)(7))
/* Variable species count */
#define NVAR             ((size_t)(5))
/* Fixed species count */
#define NFIX             ((size_t)(2))
/* Active variable species count */
#define NVARACT          ((size_t)(5))
/* Reaction (equation) count */
#define NREACT           ((size_t)(10))


/*-----------------------------------------------------------------------------*/
/* Numerical constants                                                         */
/*-----------------------------------------------------------------------------*/

#define ZERO             ((float)(0.0))
#define HALF             ((float)(0.5))
#define ONE              ((float)(1.0))
#define TWO              ((float)(2.0))


/*-----------------------------------------------------------------------------*/
/* Variable species indices                                                    */
/*-----------------------------------------------------------------------------*/

#define IND_O1D          ((size_t)(0))
#define IND_O            ((size_t)(1))
#define IND_O3           ((size_t)(2))
#define IND_NO           ((size_t)(3))
#define IND_NO2          ((size_t)(4))


/*-----------------------------------------------------------------------------*/
/* Fixed species indices                                                       */
/*-----------------------------------------------------------------------------*/

#define IND_M            ((size_t)(5))
#define IND_O2           ((size_t)(6))




#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __SMALL_PARAMETERS_H__ */
/*------------------------- END small_parameters.h END ------------------------*/
