#------------------------ BEGIN small_monitor.py BEGIN -----------------------
# @file small_monitor.py                                                      
# @author jlinford                                                            
# @date 2015-04-15 21:17:47.405914                                            
# @brief Mechanism monitoring                                                 
#                                                                             
# Species names, equations, etc.                                              
#                                                                             
# This file was generated by Kppa: http://www.paratools.com/Kppa              
#-----------------------------------------------------------------------------
import numpy as np
import sys
from small_parameters import *



#-----------------------------------------------------------------------------
# Array dimensions                                                            
#-----------------------------------------------------------------------------

# Number of species on the LOOKAT list 
NLOOKAT         =int(2)

# Number of species on the MONITOR list 
NMONITOR        =int(6)

#-----------------------------------------------------------------------------
# Species indices arrays                                                      
#-----------------------------------------------------------------------------

# Indices of species concentrations sent to data file 
ILOOKAT = np.array([ 2, 4 ])

# Indicies of species concentrations sent to screen 
IMONITOR = np.array([ 0, 1, 2, 3, 4, 6 ])

#-----------------------------------------------------------------------------
# Mechanism information                                                       
#-----------------------------------------------------------------------------

# Species names 
SPC_NAMES = [
    "O1D",
    "O",
    "O3",
    "NO",
    "NO2",
    "M",
    "O2"
]

# Equations 
EQN_NAMES = [
    "<R1>    O2 + hv --> 2 O",
    "<R2>    O + O2 --> O3",
    "<R3>    O3 + hv --> O + O2",
    "<R4>    O + O3 --> 2 O2",
    "<R5>    O3 + hv --> O1D + O2",
    "<R6>    O1D + M --> O + M",
    "<R7>    O1D + O3 --> 2 O2",
    "<R8>    NO + O3 --> NO2 + O2",
    "<R9>    NO2 + O --> NO + O2",
    "<R10>   NO2 + hv --> NO + O"
]



#-------------------------- END small_monitor.py END -------------------------
