/*------------------------- BEGIN small_solve.h BEGIN -------------------------*/
/* @file small_solve.h                                                         */
/* @author jlinford                                                            */
/* @date 2015-04-15 21:17:47.311499                                            */
/* @brief Solve Ax=b by forward-backward substitution                          */
/*                                                                             */
/* Solve Ax=b by forward-backward substitution                                 */
/*                                                                             */
/* This file was generated by Kppa: http://www.paratools.com/Kppa              */
/*-----------------------------------------------------------------------------*/

#ifndef __SMALL_SOLVE_H__
#define __SMALL_SOLVE_H__



#ifdef __cplusplus
extern "C" {
#endif


/*----------------------------------- Solve -----------------------------------*/
/* Solve Ax=b in place by back substitution                                    */
/*                                                                             */
/* @param[in]     A Row-compressed matrix with zero fill                       */
/* @param[in,out] x Input and solution vector                                  */
/*-----------------------------------------------------------------------------*/
void Solve(float const  A[JAC_LU_NZ], float x[NVAR]);



#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __SMALL_SOLVE_H__ */
/*--------------------------- END small_solve.h END ---------------------------*/
