/*------------------------- BEGIN small_rates.h BEGIN -------------------------*/
/* @file small_rates.h                                                         */
/* @author jlinford                                                            */
/* @date 2015-04-15 21:17:47.245680                                            */
/* @brief Reaction rate calculation and utility functions                      */
/*                                                                             */
/* Reaction rate calculation and utility functions                             */
/*                                                                             */
/* This file was generated by Kppa: http://www.paratools.com/Kppa              */
/*-----------------------------------------------------------------------------*/

#ifndef __SMALL_RATES_H__
#define __SMALL_RATES_H__



#ifdef __cplusplus
extern "C" {
#endif


/*----------------------------------- Rates -----------------------------------*/
/* Calculates reaction rate coefficients                                       */
/*                                                                             */
/* @param[in]     time Integration time                                        */
/* @param[in]     idx  Current grid cell index                                 */
/* @param[out]    rct  Reaction rates                                          */
/*-----------------------------------------------------------------------------*/
void Rates(float const time, size_t const idx, float rct[10]);



#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __SMALL_RATES_H__ */
/*--------------------------- END small_rates.h END ---------------------------*/
