/*----------------------- BEGIN small_integrate.h BEGIN -----------------------*/
/* @file small_integrate.h                                                     */
/* @author jlinford                                                            */
/* @date 2015-04-15 21:17:47.356960                                            */
/* @brief Interface to time stepping integrator                                */
/*                                                                             */
/* Definitions of interface functions for the Kppa-generated                   */
/* time stepping integrator.  These are the Kppa "entry point" routines.       */
/*                                                                             */
/* This file was generated by Kppa: http://www.paratools.com/Kppa              */
/*-----------------------------------------------------------------------------*/

#ifndef __SMALL_INTEGRATE_H__
#define __SMALL_INTEGRATE_H__



#ifdef __cplusplus
extern "C" {
#endif


/*------------------------------- GridIntegrate -------------------------------*/
/* Applies the Kppa-generated integrator to the grid                           */
/*                                                                             */
/* @param[in]     ncells Number of grid cells                                  */
/* @param[in,out] conc   Species concentrations                                */
/* @param[in]     tstart Integration start time                                */
/* @param[in]     tend   Integration end time                                  */
/* @param[in]     abstol Absolute integration tolerances for variable species  */
/* @param[in]     reltol Relative integration tolerances for variable species  */
/* @param[in,out] idata  Integer integration in/out parameters                 */
/* @param[in,out] rdata  Real value integration in/out parameters              */
/* @param[out]    lastH  Last timestep in each grid cell                       */
/*-----------------------------------------------------------------------------*/
int GridIntegrate(size_t const ncells, float conc[], float const tstart,
    float const tend, float const  abstol[NVAR], float const  reltol[NVAR],
    int idata[20], float rdata[20], float lastH[/* ncells */]);



#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __SMALL_INTEGRATE_H__ */
/*------------------------- END small_integrate.h END -------------------------*/
