/*------------------------ BEGIN small_jacobian.h BEGIN -----------------------*/
/* @file small_jacobian.h                                                      */
/* @author jlinford                                                            */
/* @date 2015-04-15 21:17:47.346789                                            */
/* @brief The Jacobian of the chemical model                                   */
/*                                                                             */
/* The Jacobian of the chemical model                                          */
/*                                                                             */
/* This file was generated by Kppa: http://www.paratools.com/Kppa              */
/*-----------------------------------------------------------------------------*/

#ifndef __SMALL_JACOBIAN_H__
#define __SMALL_JACOBIAN_H__



#ifdef __cplusplus
extern "C" {
#endif


/*------------------------------------ Jac ------------------------------------*/
/* The Jacobian of variable species                                            */
/*                                                                             */
/* @param[in]     var  Variable species concentrations                         */
/* @param[in]     fix  Fixed species concentrations                            */
/* @param[in]     rct  Reaction rates                                          */
/* @param[out]    sjac The row-compressed sparse Jacobian                      */
/*-----------------------------------------------------------------------------*/
void Jac(float const  var[NVAR], float const  fix[NFIX], float const
    rct[NREACT], float sjac[JAC_LU_NZ]);



#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __SMALL_JACOBIAN_H__ */
/*-------------------------- END small_jacobian.h END -------------------------*/
