/*------------------------ BEGIN small_function.h BEGIN -----------------------*/
/* @file small_function.h                                                      */
/* @author jlinford                                                            */
/* @date 2015-04-15 21:17:47.272533                                            */
/* @brief The ODE function of the chemical model                               */
/*                                                                             */
/* The ODE function of the chemical model                                      */
/*                                                                             */
/* This file was generated by Kppa: http://www.paratools.com/Kppa              */
/*-----------------------------------------------------------------------------*/

#ifndef __SMALL_FUNCTION_H__
#define __SMALL_FUNCTION_H__



#ifdef __cplusplus
extern "C" {
#endif


/*------------------------------------ Fun ------------------------------------*/
/* The ODE function of the chemical model                                      */
/*                                                                             */
/* @param[in]     var    Variable species concentrations                       */
/* @param[in]     fix    Fixed species concentrations                          */
/* @param[in]     rct    Reaction rates                                        */
/* @param[out]    vardot The ODE function                                      */
/*-----------------------------------------------------------------------------*/
void Fun(float const  var[NVAR], float const  fix[NFIX], float const
    rct[NREACT], float vardot[NVAR]);



#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __SMALL_FUNCTION_H__ */
/*-------------------------- END small_function.h END -------------------------*/
