/*------------------------- BEGIN small_decomp.h BEGIN ------------------------*/
/* @file small_decomp.h                                                        */
/* @author jlinford                                                            */
/* @date 2015-04-15 21:17:47.290937                                            */
/* @brief LU decomposition of the row-compressed sparse Jacobian               */
/*                                                                             */
/* LU decomposition of the row-compressed sparse Jacobian                      */
/*                                                                             */
/* This file was generated by Kppa: http://www.paratools.com/Kppa              */
/*-----------------------------------------------------------------------------*/

#ifndef __SMALL_DECOMP_H__
#define __SMALL_DECOMP_H__



#ifdef __cplusplus
extern "C" {
#endif


/*----------------------------------- Decomp ----------------------------------*/
/* In-place sparse LU decomposition                                            */
/*                                                                             */
/* @param[in,out] A Row-compressed matrix with zero fill                       */
/*-----------------------------------------------------------------------------*/
int Decomp(float A[JAC_LU_NZ]);



#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __SMALL_DECOMP_H__ */
/*--------------------------- END small_decomp.h END --------------------------*/
