#---------------------- BEGIN small_initialize.py BEGIN ----------------------
# @file small_initialize.py                                                   
# @author jlinford                                                            
# @date 2015-04-15 21:17:47.388230                                            
# @brief Species concentration initialization                                 
#                                                                             
# Species concentration initialization                                        
#                                                                             
# This file was generated by Kppa: http://www.paratools.com/Kppa              
#-----------------------------------------------------------------------------
import numpy as np
import sys
from small_parameters import *




#--------------------------------- Initialize --------------------------------
# Species concentration initialization.                                       
# Concentrations are usually supplied by the model from input data            
# or other calculations, not specified directly as done here.                 
#                                                                             
# @param[in,out] var Variable species concentrations                          
# @param[in,out] fix Fixed species concentrations                             
#-----------------------------------------------------------------------------
def Initialize(var, fix):
  # Variable species initialization 
  var[0] = 99.06*CFACTOR
  var[1] = 662400000.0*CFACTOR
  var[2] = 532600000000.0*CFACTOR
  var[3] = 872500000.0*CFACTOR
  var[4] = 224000000.0*CFACTOR

  # Fixed species initialization 
  fix[0] = 8.12e+16*CFACTOR
  fix[1] = 1.697e+16*CFACTOR
# END Initialize



#------------------------ END small_initialize.py END ------------------------
