#------------------- BEGIN small_driver_parameters.py BEGIN ------------------
# @file small_driver_parameters.py                                            
# @author jlinford                                                            
# @date 2015-04-15 21:17:47.396315                                            
# @brief Program driver parameters                                            
#                                                                             
# Time domain definitions and grid cell count                                 
#                                                                             
# This file was generated by Kppa: http://www.paratools.com/Kppa              
#-----------------------------------------------------------------------------
import numpy as np
import sys


#-----------------------------------------------------------------------------
# Time domain                                                                 
#-----------------------------------------------------------------------------

# Integration start time 
TSTART          =np.float32(0.0)
# Integration end time 
TEND            =np.float32(3600.0)
# Time between integrator restarts 
TDEL            =np.float32(350.0)


#-----------------------------------------------------------------------------
# Grid dimensions                                                             
#-----------------------------------------------------------------------------

# Grid dimension 0 
GRID0           =int(100)
# Grid dimension 1 
GRID1           =int(100)
# Grid dimension 2 
GRID2           =int(100)
# Number of grid cells to integrate 
NCELLS          =int(GRID0*GRID1*GRID2)



#--------------------- END small_driver_parameters.py END --------------------
